// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: console.proto

package console

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConsoleClient is the client API for Console service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsoleClient interface {
	UploadDBSCHEMA(ctx context.Context, in *SchemaParams, opts ...grpc.CallOption) (*Response, error)
	LambdaSCHEMA(ctx context.Context, in *LambdaSchemaParams, opts ...grpc.CallOption) (*LambdaSchemaResponse, error)
	RoleData(ctx context.Context, in *LambdaSchemaParams, opts ...grpc.CallOption) (*LambdaSchemaResponse, error)
}

type consoleClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleClient(cc grpc.ClientConnInterface) ConsoleClient {
	return &consoleClient{cc}
}

func (c *consoleClient) UploadDBSCHEMA(ctx context.Context, in *SchemaParams, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/console.Console/UploadDBSCHEMA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) LambdaSCHEMA(ctx context.Context, in *LambdaSchemaParams, opts ...grpc.CallOption) (*LambdaSchemaResponse, error) {
	out := new(LambdaSchemaResponse)
	err := c.cc.Invoke(ctx, "/console.Console/LambdaSCHEMA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) RoleData(ctx context.Context, in *LambdaSchemaParams, opts ...grpc.CallOption) (*LambdaSchemaResponse, error) {
	out := new(LambdaSchemaResponse)
	err := c.cc.Invoke(ctx, "/console.Console/RoleData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsoleServer is the server API for Console service.
// All implementations should embed UnimplementedConsoleServer
// for forward compatibility
type ConsoleServer interface {
	UploadDBSCHEMA(context.Context, *SchemaParams) (*Response, error)
	LambdaSCHEMA(context.Context, *LambdaSchemaParams) (*LambdaSchemaResponse, error)
	RoleData(context.Context, *LambdaSchemaParams) (*LambdaSchemaResponse, error)
}

// UnimplementedConsoleServer should be embedded to have forward compatible implementations.
type UnimplementedConsoleServer struct {
}

func (UnimplementedConsoleServer) UploadDBSCHEMA(context.Context, *SchemaParams) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadDBSCHEMA not implemented")
}
func (UnimplementedConsoleServer) LambdaSCHEMA(context.Context, *LambdaSchemaParams) (*LambdaSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LambdaSCHEMA not implemented")
}
func (UnimplementedConsoleServer) RoleData(context.Context, *LambdaSchemaParams) (*LambdaSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoleData not implemented")
}

// UnsafeConsoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleServer will
// result in compilation errors.
type UnsafeConsoleServer interface {
	mustEmbedUnimplementedConsoleServer()
}

func RegisterConsoleServer(s grpc.ServiceRegistrar, srv ConsoleServer) {
	s.RegisterService(&Console_ServiceDesc, srv)
}

func _Console_UploadDBSCHEMA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemaParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).UploadDBSCHEMA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/console.Console/UploadDBSCHEMA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).UploadDBSCHEMA(ctx, req.(*SchemaParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_LambdaSCHEMA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LambdaSchemaParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).LambdaSCHEMA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/console.Console/LambdaSCHEMA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).LambdaSCHEMA(ctx, req.(*LambdaSchemaParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_RoleData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LambdaSchemaParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).RoleData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/console.Console/RoleData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).RoleData(ctx, req.(*LambdaSchemaParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Console_ServiceDesc is the grpc.ServiceDesc for Console service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Console_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "console.Console",
	HandlerType: (*ConsoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadDBSCHEMA",
			Handler:    _Console_UploadDBSCHEMA_Handler,
		},
		{
			MethodName: "LambdaSCHEMA",
			Handler:    _Console_LambdaSCHEMA_Handler,
		},
		{
			MethodName: "RoleData",
			Handler:    _Console_RoleData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "console.proto",
}
