// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: lambda.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table  string  `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Key    string  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Field  string  `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Values []int32 `protobuf:"varint,4,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *TableOption) Reset() {
	*x = TableOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lambda_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableOption) ProtoMessage() {}

func (x *TableOption) ProtoReflect() protoreflect.Message {
	mi := &file_lambda_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableOption.ProtoReflect.Descriptor instead.
func (*TableOption) Descriptor() ([]byte, []int) {
	return file_lambda_proto_rawDescGZIP(), []int{0}
}

func (x *TableOption) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *TableOption) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TableOption) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *TableOption) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type IntRows struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*IntRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *IntRows) Reset() {
	*x = IntRows{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lambda_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntRows) ProtoMessage() {}

func (x *IntRows) ProtoReflect() protoreflect.Message {
	mi := &file_lambda_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntRows.ProtoReflect.Descriptor instead.
func (*IntRows) Descriptor() ([]byte, []int) {
	return file_lambda_proto_rawDescGZIP(), []int{1}
}

func (x *IntRows) GetRows() []*IntRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type IntRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   int32 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value int32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *IntRow) Reset() {
	*x = IntRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lambda_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntRow) ProtoMessage() {}

func (x *IntRow) ProtoReflect() protoreflect.Message {
	mi := &file_lambda_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntRow.ProtoReflect.Descriptor instead.
func (*IntRow) Descriptor() ([]byte, []int) {
	return file_lambda_proto_rawDescGZIP(), []int{2}
}

func (x *IntRow) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *IntRow) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StringRows struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*StringRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *StringRows) Reset() {
	*x = StringRows{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lambda_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringRows) ProtoMessage() {}

func (x *StringRows) ProtoReflect() protoreflect.Message {
	mi := &file_lambda_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringRows.ProtoReflect.Descriptor instead.
func (*StringRows) Descriptor() ([]byte, []int) {
	return file_lambda_proto_rawDescGZIP(), []int{3}
}

func (x *StringRows) GetRows() []*StringRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type StringRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   int32  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StringRow) Reset() {
	*x = StringRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lambda_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringRow) ProtoMessage() {}

func (x *StringRow) ProtoReflect() protoreflect.Message {
	mi := &file_lambda_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringRow.ProtoReflect.Descriptor instead.
func (*StringRow) Descriptor() ([]byte, []int) {
	return file_lambda_proto_rawDescGZIP(), []int{4}
}

func (x *StringRow) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *StringRow) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_lambda_proto protoreflect.FileDescriptor

var file_lambda_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x22, 0x63, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x07, 0x49,
	0x6e, 0x74, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x2e, 0x49, 0x6e,
	0x74, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x30, 0x0a, 0x06, 0x49, 0x6e,
	0x74, 0x52, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x33, 0x0a, 0x0a,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64,
	0x61, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77,
	0x73, 0x22, 0x33, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x77, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x7a, 0x0a, 0x06, 0x4c, 0x61, 0x6d, 0x62, 0x64, 0x61,
	0x12, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x13,
	0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x0f, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x2e, 0x49, 0x6e, 0x74,
	0x52, 0x6f, 0x77, 0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x13, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61,
	0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x12, 0x2e, 0x6c,
	0x61, 0x6d, 0x62, 0x64, 0x61, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x77, 0x73,
	0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lambda_proto_rawDescOnce sync.Once
	file_lambda_proto_rawDescData = file_lambda_proto_rawDesc
)

func file_lambda_proto_rawDescGZIP() []byte {
	file_lambda_proto_rawDescOnce.Do(func() {
		file_lambda_proto_rawDescData = protoimpl.X.CompressGZIP(file_lambda_proto_rawDescData)
	})
	return file_lambda_proto_rawDescData
}

var file_lambda_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_lambda_proto_goTypes = []interface{}{
	(*TableOption)(nil), // 0: lambda.TableOption
	(*IntRows)(nil),     // 1: lambda.IntRows
	(*IntRow)(nil),      // 2: lambda.IntRow
	(*StringRows)(nil),  // 3: lambda.StringRows
	(*StringRow)(nil),   // 4: lambda.StringRow
}
var file_lambda_proto_depIdxs = []int32{
	2, // 0: lambda.IntRows.rows:type_name -> lambda.IntRow
	4, // 1: lambda.StringRows.rows:type_name -> lambda.StringRow
	0, // 2: lambda.Lambda.GetIntData:input_type -> lambda.TableOption
	0, // 3: lambda.Lambda.GetStringData:input_type -> lambda.TableOption
	1, // 4: lambda.Lambda.GetIntData:output_type -> lambda.IntRows
	3, // 5: lambda.Lambda.GetStringData:output_type -> lambda.StringRows
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lambda_proto_init() }
func file_lambda_proto_init() {
	if File_lambda_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lambda_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lambda_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntRows); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lambda_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lambda_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringRows); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lambda_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lambda_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lambda_proto_goTypes,
		DependencyIndexes: file_lambda_proto_depIdxs,
		MessageInfos:      file_lambda_proto_msgTypes,
	}.Build()
	File_lambda_proto = out.File
	file_lambda_proto_rawDesc = nil
	file_lambda_proto_goTypes = nil
	file_lambda_proto_depIdxs = nil
}
